language: node_js
node_js:
  - '10'
addons:
  postgresql: '9.6'
services:
  - postgresql
  - redis-server
before_script:
  - psql -c 'CREATE DATABASE eflow_test;' -U postgres
  - npm run global add node-gyp
script:
  - npm run lint
  - npm run test-cover
  - npm run test-coverage
after_script: npm run coveralls
